### ISSUE TITLE
Its broke - cant install

### ISSUE THREAD

**Issue by virgesmith** [Robinlovelace/ukboundaries#5]
** testing if installed package can be loaded
Error: package or namespace load failed for ‘ukboundaries’:
 .onLoad failed in loadNamespace() for 'ukboundaries', details:
  call: cols(Coverage = col_character(), Geography = col_character(), 
  error: could not find function "cols"
Error: loading failed
Execution halted
ERROR: loading failed

**Comment by virgesmith** [comment]
@Robinlovelace the fix is: add readr to Depends: in DESCRIPTION
But I dont have write permish...

**Comment by Robinlovelace** [comment]
I think I've given you write access...

**Comment by Robinlovelace** [comment]
readr is imported... I can see the issue - it should be `readr::cols` - will look to fix that now.
